name: GitHub Actions
on: [push]
jobs:
    Test_JS:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node_version: [16.x]
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: run tests
              run: |
                  cd appliance_status_js
                  yarn
                  yarn test
    Test_PY:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python_version: [3.9]
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: run tests
              run: |
                  cd appliance_status_py
                  python -m venv .
                  source ./bin/activate
                  make test

